[build]
  base = "client/"
  command = "npm run-script build"
  publish = "client/build/"
[[redirects]]
  from = "/sw.js"
  to = "/service-worker.js"
  status = 200
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200