name: "Back-end deploy"
on: [push]
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Push new release
        env:
          REMOTE_PUBLIC_KEY: ${{ secrets.REMOTE_PUBLIC_KEY }}
          REMOTE_URL: ${{ secrets.REMOTE_URL }}
        run: |
          echo "$REMOTE_PUBLIC_KEY" >> ~/.ssh/known_hosts
          git subtree split --prefix api -b api
          git push -f $REMOTE_URL api:master
