name: deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_URL }}
          REMOTE_URL: ${{ secrets.REMOTE_URL }}
        run: |
          ssh-add - <<< "$PRIVATE_KEY"
          git subtree push --prefix api $REMOTE_URL master
